<?xml version="1.0" encoding="UTF-8"?>
<ns1:PricesimulationResponse xmlns:jms1="http://www.tibco.com/namespaces/tnt/plugins/jms" xmlns:ns1="http://postnord.com/SFDC/PriceSimulation">
    <FaultData xmlns="">
         <faultDetail>
            <severity>E</severity>
            <text>Der findes ingen kundestamdata for kunde 10003141</text>
        </faultDetail>
    </FaultData>
</ns1:PricesimulationResponse>